#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#if [ "$0" = "/usr/sbin/lightdm-session" -a "$DESKTOP_SESSION" = "i3" ]; then
#	    export $(gnome-keyring-daemon -s)
#fi

#if [ -n "$DESKTOP_SESSION" ];then
#  eval $(gnome-keyring-daemon --start --components=ssh)
#  export SSH_AUTH_SOCK
#fi

